name: CI - Auditoría y SAST
on: [push, pull_request, workflow_dispatch]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Ejecutar auditoría
        run: python3 rules/auditor_completo.py .
      - uses: actions/upload-artifact@v7
        with:
          name: report
          path: reporte_final.json
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Semgrep
        run: pip install semgrep
      - name: Ejecutar SAST
        run: semgrep --config ./rules/semgrep/ --json -o sast-report.json .
      - uses: actions/upload-artifact@v7
        with:
          name: sast-report
          path: sast-report.json